version: "3.9"

services:
  app:
    build: .
    container_name: go-warmup
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017/go-warmup?authSource=admin
      - MONGO_DB=go-warmup
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: go-warmup
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d:ro

volumes:
  mongo-data:
